In [3]:
#1. Импорт библиотеки NumPy с общепринятым сокращением.
import numpy as np

In [17]:
#2. Примеры создания массивов

#- из обычных списков;
arrInt = np.array([1, 2, 3]) #Обычный 1D массив с целочисленными значениями
arrString = np.array(["abc", "acb", "bac"]) #Обычный 1D массив с строковыми значениями
matrixInt = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) #2D массив с целочисленными значениями

#- с использованием функций `zeros`, `ones`, `arange` или аналогичных.
arrZeros = np.zeros(5) #Массив из 5 нулей
arrOnes = np.ones(5) #Массив из 5 единиц
arrRange = np.arange(0, 10, 2, int) #Массив от 0 до 10 не включительно с шагом 2

print(arrInt, arrString, matrixInt, arrZeros, arrOnes, arrRange, sep='\n')

[1 2 3]
['abc' 'acb' 'bac']
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[0 2 4 6 8]


In [18]:
#3. Демонстрация атрибутов

#- вывод формы (shape) и типа данных (dtype) для одного из массивов.
print(matrixInt.shape, matrixInt.dtype, sep='\n') #Вывод размерности матрицы и типа данных, содержащихся в ней

(3, 3)
int64


In [22]:
#4. Примеры индексирования и срезов:

#- получение отдельного элемента;
print(arrInt[0], arrInt[1], arrInt[-1])

#-Извлечение подмассива с помощью среда
print(arrRange[1:4])

1 2 3
[2 4 6]


In [32]:
#5. Примеры векторных операций и базовых статистик

#- поэлементное сложение или умножение массивов;
matrixInt2 = np.array([np.ones(3), np.ones(3), np.ones(3)]) #Создадим вторую матрицу 3х3 для демонстрации сложения двух 2д массивов
matrixSum = matrixInt + matrixInt2 #Вычисляем сумму двух матриц
matrixProduct = matrixInt * matrixInt2 #Вычисляем произведение двух матриц
print(matrixSum, matrixProduct, sep='\n')

#- вычисление средней величины (`mean`) или другой простой статистики.
print(matrixSum.mean()) #Вычисление среднего значения
print(matrixSum.min()) #Вычсиление минимального значения
print(matrixSum.max()) #Вычисление максимального значения

[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
6.0
2.0
10.0
